/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import query.JDlgConsultaCompra;
import query.JDlgConsultaFornecedor;
import query.JDlgConsultaPagamento;
import query.JDlgConsultaProduto;

/**
 *
 * @author u71665822198
 */
public class JFrmPrincipal_gab extends javax.swing.JFrame {

    /**
     * Creates new form JFrmPrincipal
     */
    public JFrmPrincipal_gab(){
        initComponents();
        setTitle("Vendas de Roupas");
        setExtendedState(MAXIMIZED_BOTH);
        
    }

    public JFrmPrincipal_gab(Object object, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        toolProduto = new javax.swing.JButton();
        toolbarForncedor = new javax.swing.JButton();
        toolbarPagamento = new javax.swing.JButton();
        toolCompras = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMnuCadastros = new javax.swing.JMenu();
        jMnuUsuarios = new javax.swing.JMenuItem();
        jMnuFornecedor = new javax.swing.JMenuItem();
        jMnuProdutos = new javax.swing.JMenuItem();
        jMnuPagamento = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMnuSair = new javax.swing.JMenuItem();
        jMnuCompra = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vendas de Roupas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        toolProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/open-box.png"))); // NOI18N
        toolProduto.setFocusable(false);
        toolProduto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolProduto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolProdutoActionPerformed(evt);
            }
        });
        jPanel1.add(toolProduto);

        toolbarForncedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/fornecedor.png"))); // NOI18N
        toolbarForncedor.setFocusable(false);
        toolbarForncedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolbarForncedor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbarForncedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolbarForncedorActionPerformed(evt);
            }
        });
        jPanel1.add(toolbarForncedor);

        toolbarPagamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/payment-method.png"))); // NOI18N
        toolbarPagamento.setFocusable(false);
        toolbarPagamento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolbarPagamento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbarPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolbarPagamentoActionPerformed(evt);
            }
        });
        jPanel1.add(toolbarPagamento);

        toolCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/trade.png"))); // NOI18N
        toolCompras.setFocusable(false);
        toolCompras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolCompras.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolComprasActionPerformed(evt);
            }
        });
        jPanel1.add(toolCompras);

        jMnuCadastros.setText("Cadastros");

        jMnuUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMnuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/cliente_1.png"))); // NOI18N
        jMnuUsuarios.setMnemonic('U');
        jMnuUsuarios.setText("Usuários");
        jMnuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuUsuariosActionPerformed(evt);
            }
        });
        jMnuCadastros.add(jMnuUsuarios);

        jMnuFornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMnuFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/fornecedor.png"))); // NOI18N
        jMnuFornecedor.setMnemonic('F');
        jMnuFornecedor.setText("Fornecedor");
        jMnuFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuFornecedorActionPerformed(evt);
            }
        });
        jMnuCadastros.add(jMnuFornecedor);

        jMnuProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMnuProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/open-box.png"))); // NOI18N
        jMnuProdutos.setMnemonic('P');
        jMnuProdutos.setText("Produto");
        jMnuProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuProdutosActionPerformed(evt);
            }
        });
        jMnuCadastros.add(jMnuProdutos);

        jMnuPagamento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMnuPagamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/aperto-de-mao.png"))); // NOI18N
        jMnuPagamento.setMnemonic('P');
        jMnuPagamento.setText("Pagamento");
        jMnuPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuPagamentoActionPerformed(evt);
            }
        });
        jMnuCadastros.add(jMnuPagamento);
        jMnuCadastros.add(jSeparator1);

        jMnuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMnuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/exit.png"))); // NOI18N
        jMnuSair.setMnemonic('S');
        jMnuSair.setText("Sair");
        jMnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuSairActionPerformed(evt);
            }
        });
        jMnuCadastros.add(jMnuSair);

        jMenuBar1.add(jMnuCadastros);

        jMnuCompra.setText("Movimento");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/payment-method.png"))); // NOI18N
        jMenuItem1.setText("Compra");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMnuCompra.add(jMenuItem1);

        jMenuBar1.add(jMnuCompra);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 226, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowActivated

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    JDlgCompra_gab  jDlgCompra = new JDlgCompra_gab(null,true);
     jDlgCompra.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMnuSairActionPerformed

    private void jMnuPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuPagamentoActionPerformed
        // TODO add your handling code here:
                JDlgPagamentoNovo_gab  jDlgPagamentoNovo = new JDlgPagamentoNovo_gab(null,true);
                jDlgPagamentoNovo.setVisible(true);
    }//GEN-LAST:event_jMnuPagamentoActionPerformed

    private void jMnuProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuProdutosActionPerformed
        // TODO add your handling code here:
                JDlgProdutoNovo_gab  jDlgProdutosNovo = new JDlgProdutoNovo_gab (null,true);
                jDlgProdutosNovo.setVisible(true);
    }//GEN-LAST:event_jMnuProdutosActionPerformed

    private void jMnuFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuFornecedorActionPerformed
        // TODO add your handling code here:
                JDlgFornecedor_gab  jDlgFornecedor = new JDlgFornecedor_gab (null, true);
                jDlgFornecedor.setVisible(true);
    }//GEN-LAST:event_jMnuFornecedorActionPerformed

    private void jMnuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuUsuariosActionPerformed
        // TODO add your handling code here:
                    JDlgUsuarios_gab  jDlgUsuarios = new JDlgUsuarios_gab (null, true);
                    jDlgUsuarios.setVisible(true);
    }//GEN-LAST:event_jMnuUsuariosActionPerformed

    private void toolbarForncedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolbarForncedorActionPerformed
        // TODO add your handling code here:
        JDlgConsultaFornecedor jDlgFornecedor = new JDlgConsultaFornecedor(null, true);
        jDlgFornecedor.setVisible(true);
    }//GEN-LAST:event_toolbarForncedorActionPerformed

    private void toolbarPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolbarPagamentoActionPerformed
        // TODO add your handling code here:
        JDlgConsultaPagamento jDlgConsultaPagamento = new JDlgConsultaPagamento(null, true);
        jDlgConsultaPagamento.setVisible(true);
    }//GEN-LAST:event_toolbarPagamentoActionPerformed

    private void toolProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolProdutoActionPerformed
        // TODO add your handling code here:
        JDlgConsultaProduto jDlgProduto = new JDlgConsultaProduto(null, true);
        jDlgProduto.setVisible(true);
    }//GEN-LAST:event_toolProdutoActionPerformed

    private void toolComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolComprasActionPerformed
        // TODO add your handling code here:
         JDlgConsultaCompra jDlgConsultaCompra = new JDlgConsultaCompra(null, true);
        jDlgConsultaCompra.setVisible(true);
    }//GEN-LAST:event_toolComprasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal_gab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal_gab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal_gab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal_gab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmPrincipal_gab().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jMnuCadastros;
    private javax.swing.JMenu jMnuCompra;
    private javax.swing.JMenuItem jMnuFornecedor;
    private javax.swing.JMenuItem jMnuPagamento;
    private javax.swing.JMenuItem jMnuProdutos;
    private javax.swing.JMenuItem jMnuSair;
    private javax.swing.JMenuItem jMnuUsuarios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JButton toolCompras;
    private javax.swing.JButton toolProduto;
    private javax.swing.JButton toolbarForncedor;
    private javax.swing.JButton toolbarPagamento;
    // End of variables declaration//GEN-END:variables
}
