package bean;
// Generated 16/09/2023 15:46:14 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CompraGab generated by hbm2java
 */
@Entity
@Table(name="compra_gab"
    ,catalog="db_gustavo_barros"
)
public class CompraGab  implements java.io.Serializable {


     private int idCompraGab;
     private FornecedorGab fornecedorGab;
     private Date dataGab;
     private String nomeProdutoGab;
     private double valorGab;
     private Set compraprodutoGabs = new HashSet(0);

    public CompraGab() {
    }

	
    public CompraGab(int idCompraGab, FornecedorGab fornecedorGab, Date dataGab, String nomeProdutoGab, double valorGab) {
        this.idCompraGab = idCompraGab;
        this.fornecedorGab = fornecedorGab;
        this.dataGab = dataGab;
        this.nomeProdutoGab = nomeProdutoGab;
        this.valorGab = valorGab;
    }
    public CompraGab(int idCompraGab, FornecedorGab fornecedorGab, Date dataGab, String nomeProdutoGab, double valorGab, Set compraprodutoGabs) {
       this.idCompraGab = idCompraGab;
       this.fornecedorGab = fornecedorGab;
       this.dataGab = dataGab;
       this.nomeProdutoGab = nomeProdutoGab;
       this.valorGab = valorGab;
       this.compraprodutoGabs = compraprodutoGabs;
    }
   
     @Id 

    
    @Column(name="idCompra_gab", unique=true, nullable=false)
    public int getIdCompraGab() {
        return this.idCompraGab;
    }
    
    public void setIdCompraGab(int idCompraGab) {
        this.idCompraGab = idCompraGab;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_Fornecedor_gab", nullable=false)
    public FornecedorGab getFornecedorGab() {
        return this.fornecedorGab;
    }
    
    public void setFornecedorGab(FornecedorGab fornecedorGab) {
        this.fornecedorGab = fornecedorGab;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_gab", nullable=false, length=10)
    public Date getDataGab() {
        return this.dataGab;
    }
    
    public void setDataGab(Date dataGab) {
        this.dataGab = dataGab;
    }

    
    @Column(name="nomeProduto_gab", nullable=false, length=45)
    public String getNomeProdutoGab() {
        return this.nomeProdutoGab;
    }
    
    public void setNomeProdutoGab(String nomeProdutoGab) {
        this.nomeProdutoGab = nomeProdutoGab;
    }

    
    @Column(name="valor_gab", nullable=false, precision=22, scale=0)
    public double getValorGab() {
        return this.valorGab;
    }
    
    public void setValorGab(double valorGab) {
        this.valorGab = valorGab;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="compraGab")
    public Set getCompraprodutoGabs() {
        return this.compraprodutoGabs;
    }
    
    public void setCompraprodutoGabs(Set compraprodutoGabs) {
        this.compraprodutoGabs = compraprodutoGabs;
    }




}


