package bean;
// Generated 16/09/2023 15:46:14 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CompraprodutoGab generated by hbm2java
 */
@Entity
@Table(name="compraproduto_gab"
    ,catalog="db_gustavo_barros"
)
public class CompraprodutoGab  implements java.io.Serializable {


     private int idCompraProdutoGab;
     private CompraGab compraGab;
     private ProdutoGab produtoGab;
     private int quantidadeGab;
     private String valorUnitarioGab;

    public CompraprodutoGab() {
    }

    public CompraprodutoGab(int idCompraProdutoGab, CompraGab compraGab, ProdutoGab produtoGab, int quantidadeGab, String valorUnitarioGab) {
       this.idCompraProdutoGab = idCompraProdutoGab;
       this.compraGab = compraGab;
       this.produtoGab = produtoGab;
       this.quantidadeGab = quantidadeGab;
       this.valorUnitarioGab = valorUnitarioGab;
    }
   
     @Id 

    
    @Column(name="idCompraProduto_gab", unique=true, nullable=false)
    public int getIdCompraProdutoGab() {
        return this.idCompraProdutoGab;
    }
    
    public void setIdCompraProdutoGab(int idCompraProdutoGab) {
        this.idCompraProdutoGab = idCompraProdutoGab;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_Compra_gab", nullable=false)
    public CompraGab getCompraGab() {
        return this.compraGab;
    }
    
    public void setCompraGab(CompraGab compraGab) {
        this.compraGab = compraGab;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_Produto_gab", nullable=false)
    public ProdutoGab getProdutoGab() {
        return this.produtoGab;
    }
    
    public void setProdutoGab(ProdutoGab produtoGab) {
        this.produtoGab = produtoGab;
    }

    
    @Column(name="quantidade_gab", nullable=false)
    public int getQuantidadeGab() {
        return this.quantidadeGab;
    }
    
    public void setQuantidadeGab(int quantidadeGab) {
        this.quantidadeGab = quantidadeGab;
    }

    
    @Column(name="valorUnitario_gab", nullable=false, length=45)
    public String getValorUnitarioGab() {
        return this.valorUnitarioGab;
    }
    
    public void setValorUnitarioGab(String valorUnitarioGab) {
        this.valorUnitarioGab = valorUnitarioGab;
    }




}


