package bean;
// Generated 08/12/2023 20:59:02 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CompraprodutoGab generated by hbm2java
 */
@Entity
@Table(name="compraproduto_gab"
    ,catalog="db_gustavo_barros"
)
public class CompraprodutoGab  implements java.io.Serializable {


     private Integer idcompraProdutoGab;
     private CompraGab compraGab;
     private ProdutoGab produtoGab;
     private int quantidadeGab;
     private double valorUnitario;

    public CompraprodutoGab() {
    }
    
    public CompraprodutoGab(int idcompraProdutoGab, int quantidadeGab, double valorUnitario) {
       this.idcompraProdutoGab = idcompraProdutoGab;
       this.quantidadeGab = quantidadeGab;
       this.valorUnitario = valorUnitario;
    }
    

    public CompraprodutoGab(int idcompraProdutoGab, CompraGab compraGab, ProdutoGab produtoGab, int quantidadeGab, double valorUnitario) {
       this.idcompraProdutoGab = idcompraProdutoGab;
       this.compraGab = compraGab;
       this.produtoGab = produtoGab;
       this.quantidadeGab = quantidadeGab;
       this.valorUnitario = valorUnitario;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idcompraProduto_gab", unique=true, nullable=false)
    public Integer getIdcompraProdutoGab() {
        return this.idcompraProdutoGab;
    }
    
    public void setIdcompraProdutoGab(Integer idcompraProdutoGab) {
        this.idcompraProdutoGab = idcompraProdutoGab;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="fk_Compra_gab")
    public CompraGab getCompraGab() {
        return this.compraGab;
    }
    
    public void setCompraGab(CompraGab compraGab) {
        this.compraGab = compraGab;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="fk_Produto_gab")
    public ProdutoGab getProdutoGab() {
        return this.produtoGab;
    }
    
    public void setProdutoGab(ProdutoGab produtoGab) {
        this.produtoGab = produtoGab;
    }

    
    @Column(name="quantidade_gab", nullable=false)
    public int getQuantidadeGab() {
        return this.quantidadeGab;
    }
    
    public void setQuantidadeGab(int quantidadeGab) {
        this.quantidadeGab = quantidadeGab;
    }

    
    @Column(name="valorUnitario", nullable=false, precision=22, scale=0)
    public double getValorUnitario() {
        return this.valorUnitario;
    }
    
    public void setValorUnitario(double valorUnitario) {
        this.valorUnitario = valorUnitario;
    }




}


