package bean;
// Generated 29/08/2023 10:54:47 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OsProdutos generated by hbm2java
 */
@Entity
@Table(name="os_produtos"
    ,catalog="mpv_aluno"
)
public class OsProdutos  implements java.io.Serializable {


     private int idosProdutos;
     private Os os;
     private Produtos produtos;
     private Integer quantidade;
     private BigDecimal valorUnitario;

    public OsProdutos() {
    }

	
    public OsProdutos(int idosProdutos) {
        this.idosProdutos = idosProdutos;
    }
    public OsProdutos(int idosProdutos, Os os, Produtos produtos, Integer quantidade, BigDecimal valorUnitario) {
       this.idosProdutos = idosProdutos;
       this.os = os;
       this.produtos = produtos;
       this.quantidade = quantidade;
       this.valorUnitario = valorUnitario;
    }
   
     @Id 

    
    @Column(name="idos_produtos", unique=true, nullable=false)
    public int getIdosProdutos() {
        return this.idosProdutos;
    }
    
    public void setIdosProdutos(int idosProdutos) {
        this.idosProdutos = idosProdutos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ok")
    public Os getOs() {
        return this.os;
    }
    
    public void setOs(Os os) {
        this.os = os;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="produtos")
    public Produtos getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Produtos produtos) {
        this.produtos = produtos;
    }

    
    @Column(name="quantidade")
    public Integer getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(Integer quantidade) {
        this.quantidade = quantidade;
    }

    
    @Column(name="valorUnitario", precision=10)
    public BigDecimal getValorUnitario() {
        return this.valorUnitario;
    }
    
    public void setValorUnitario(BigDecimal valorUnitario) {
        this.valorUnitario = valorUnitario;
    }




}


