package bean;
// Generated 29/08/2023 10:54:47 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OsServicos generated by hbm2java
 */
@Entity
@Table(name="os_servicos"
    ,catalog="mpv_aluno"
)
public class OsServicos  implements java.io.Serializable {


     private OsServicosId id;
     private Servicos servicosByIdos;
     private Servicos servicosByServicos;
     private Integer quantidade;
     private BigDecimal valorUnitario;

    public OsServicos() {
    }

	
    public OsServicos(OsServicosId id, Servicos servicosByIdos, Servicos servicosByServicos) {
        this.id = id;
        this.servicosByIdos = servicosByIdos;
        this.servicosByServicos = servicosByServicos;
    }
    public OsServicos(OsServicosId id, Servicos servicosByIdos, Servicos servicosByServicos, Integer quantidade, BigDecimal valorUnitario) {
       this.id = id;
       this.servicosByIdos = servicosByIdos;
       this.servicosByServicos = servicosByServicos;
       this.quantidade = quantidade;
       this.valorUnitario = valorUnitario;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idos", column=@Column(name="idos", nullable=false) ), 
        @AttributeOverride(name="servicos", column=@Column(name="servicos", nullable=false) ) } )
    public OsServicosId getId() {
        return this.id;
    }
    
    public void setId(OsServicosId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idos", nullable=false, insertable=false, updatable=false)
    public Servicos getServicosByIdos() {
        return this.servicosByIdos;
    }
    
    public void setServicosByIdos(Servicos servicosByIdos) {
        this.servicosByIdos = servicosByIdos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="servicos", nullable=false, insertable=false, updatable=false)
    public Servicos getServicosByServicos() {
        return this.servicosByServicos;
    }
    
    public void setServicosByServicos(Servicos servicosByServicos) {
        this.servicosByServicos = servicosByServicos;
    }

    
    @Column(name="quantidade")
    public Integer getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(Integer quantidade) {
        this.quantidade = quantidade;
    }

    
    @Column(name="valor_unitario", precision=10)
    public BigDecimal getValorUnitario() {
        return this.valorUnitario;
    }
    
    public void setValorUnitario(BigDecimal valorUnitario) {
        this.valorUnitario = valorUnitario;
    }




}


