package bean;
// Generated 21/09/2023 17:27:29 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PagamentoGab generated by hbm2java
 */
@Entity
@Table(name="pagamento_gab"
    ,catalog="db_gustavo_barros"
)
public class PagamentoGab  implements java.io.Serializable {


     private int idPagamentoGab;
     private Date dataPagamentoGab;
     private int parcelasGab;
     private int formaPagamento;
     private String valorGab;

    public PagamentoGab() {
    }

    public PagamentoGab(int idPagamentoGab, Date dataPagamentoGab, int parcelasGab, int formaPagamento, String valorGab) {
       this.idPagamentoGab = idPagamentoGab;
       this.dataPagamentoGab = dataPagamentoGab;
       this.parcelasGab = parcelasGab;
       this.formaPagamento = formaPagamento;
       this.valorGab = valorGab;
    }
   
     @Id

    
    @Column(name="idPagamento_gab", unique=true, nullable=false)
    public int getIdPagamentoGab() {
        return this.idPagamentoGab;
    }
    
    public void setIdPagamentoGab(int idPagamentoGab) {
        this.idPagamentoGab = idPagamentoGab;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataPagamento_gab", nullable=false, length=10)
    public Date getDataPagamentoGab() {
        return this.dataPagamentoGab;
    }
    
    public void setDataPagamentoGab(Date dataPagamentoGab) {
        this.dataPagamentoGab = dataPagamentoGab;
    }

    
    @Column(name="parcelas_gab", nullable=false)
    public int getParcelasGab() {
        return this.parcelasGab;
    }
    
    public void setParcelasGab(int parcelasGab) {
        this.parcelasGab = parcelasGab;
    }

    
    @Column(name="formaPagamento", nullable=false)
    public int getFormaPagamento() {
        return this.formaPagamento;
    }
    
    public void setFormaPagamento(int formaPagamento) {
        this.formaPagamento = formaPagamento;
    }

    
    @Column(name="valor_gab", nullable=false, precision=22, scale=0)
    public String getValorGab() {
        return this.valorGab;
    }
    
    public void setValorGab(String valorGab) {
        this.valorGab = valorGab;
    }




}


