package bean;
// Generated 21/09/2023 17:27:29 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProdutoGab generated by hbm2java
 */
@Entity
@Table(name="produto_gab"
    ,catalog="db_gustavo_barros"
)
public class ProdutoGab  implements java.io.Serializable {


     private int idProdutoGab;
     private String nomeGab;
     private String descricaoGab;
     private String valorGab;
     private int tamanhoGab;
     private int categoriaGab;

    public ProdutoGab() {
    }

	
    public ProdutoGab(int idProdutoGab, String nomeGab, String descricaoGab, String valorGab, int tamanhoGab, int categoriaGab) {
        this.idProdutoGab = idProdutoGab;
        this.nomeGab = nomeGab;
        this.descricaoGab = descricaoGab;
        this.valorGab = valorGab;
        this.tamanhoGab = tamanhoGab;
        this.categoriaGab = categoriaGab;
    }
   
     @Id

    
    @Column(name="idProduto_gab", unique=true, nullable=false)
    public int getIdProdutoGab() {
        return this.idProdutoGab;
    }
    
    public void setIdProdutoGab(int idProdutoGab) {
        this.idProdutoGab = idProdutoGab;
    }

    
    @Column(name="nome_gab", nullable=false, length=45)
    public String getNomeGab() {
        return this.nomeGab;
    }
    
    public void setNomeGab(String nomeGab) {
        this.nomeGab = nomeGab;
    }

    
    @Column(name="descricao_gab", nullable=false, length=150)
    public String getDescricaoGab() {
        return this.descricaoGab;
    }
    
    public void setDescricaoGab(String descricaoGab) {
        this.descricaoGab = descricaoGab;
    }

    
    @Column(name="valor_gab", nullable=false, precision=22, scale=0)
    public String getValorGab() {
        return this.valorGab;
    }
    
    public void setValorGab(String valorGab) {
        this.valorGab = valorGab;
    }

    
    @Column(name="tamanho_gab", nullable=false)
    public int getTamanhoGab() {
        return this.tamanhoGab;
    }
    
    public void setTamanhoGab(int tamanhoGab) {
        this.tamanhoGab = tamanhoGab;
    }

    
    @Column(name="categoria_gab", nullable=false)
    public int getCategoriaGab() {
        return this.categoriaGab;
    }
    
    public void setCategoriaGab(int categoriaGab) {
        this.categoriaGab = categoriaGab;
    }

    @Override
    public String toString(){
        return getNomeGab();
    }

}


